spring:
  datasource:
    url: jdbc:h2:file:./data/insurance-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  messages:
    basename: message
    encoding: UTF-8

security:
  auth:
    tokens:
      - b1927470-5dc1-4cc4-a566-6fa546f14d5d
      - fb8dc7c6-2b07-4f39-89fe-c2cb4d00018a
      - 5309d285-7bec-4eff-8ba3-db3dbffe1238
